# This is a config for E2B sandbox template.
# You can use template ID (vwd2ca017a6hxkh0du8y) or template name (viy-nextjs-demo) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("viy-nextjs-demo") # Sync sandbox
# sandbox = await AsyncSandbox.create("viy-nextjs-demo") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('viy-nextjs-demo')

team_id = "3fda0233-c0c5-4564-8525-5ea00821b75e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "viy-nextjs-demo"
template_id = "vwd2ca017a6hxkh0du8y"
